### ISSUE TITLE
Alterar localização de receita por ingredientes

### ISSUE THREAD

**Issue by 1989Dias** [marcelomene/rangoja#1]
## Local:
GetRecipesIdsThatContainsIngredients()

## Alterações:
string sqlQuery = $"SELECT IdRecipe FROM Recipe_Ingredients";
string sqlWhere = " WHERE IdIngredient IN";
string sqlIN = "";

for(int i = 0; i < ingredients.Count - 1; i++ )
sqlIN += $"{ingredients[i].Id},"
//sqlQuery += $"IdIngredient = {ingredients[i].Id} OR ";
//sqlQuery += $"IdIngredient = {ingredients[ingredients.Count - 1].Id}";

sqlQuery += sqlWhere + "(" + sqlIN + ")"

**Comment by marcelomene** [comment]
Done
