### ISSUE TITLE
Modificação na select da consulta 🎉

### ISSUE THREAD

**Issue by 1989Dias** [marcelomene/rangoja#3]
public static List<int> GetRecipesIdsThatContainsIngredients(List<Ingredient> ingredients)
        {
            List<int> recipeIds = new List<int>();
            
            string sqlQuery = $"SELECT IdRecipe FROM Recipe_Ingredients";
            string sqlWhere = " WHERE IdIngredient IN";
            string sqlIN = "";

            for (int i = 0; i < ingredients.Count; i++)
            {                
                sqlIN += $"{ingredients[i].Id},";                
            }

            sqlQuery += sqlWhere + "(" + sqlIN.Remove(sqlIN.Length - 1, 1) + ")";
            sqlQuery += " group by IdRecipe";

            Connection.Open();

            MySqlCommand cmd = Connection.CreateCommand();
            cmd.CommandText = sqlQuery;
            MySqlDataReader reader = cmd.ExecuteReader();

            while (reader.Read())
                recipeIds.Add((int)reader["IdRecipe"]);

            Connection.Close();

            return recipeIds;
        }

**Comment by marcelomene** [comment]
Done
